spring:
  data:
    redis:
      host: ${REDIS_HOST:192.168.194.250}
      port: ${REDIS_PORT:6379}
  
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:192.168.194.250:9092}
    consumer:
      group-id: proxy-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

logging:
  level:
    ROOT: INFO
    com.celi.proxy: DEBUG
    org.springframework.kafka: INFO
    org.springframework.data.redis: DEBUG

application:
  backend:
    url: ${BACKEND_URL:http://localhost:8080}
  catedra:
    url: ${CATEDRA_URL:http://192.168.194.250:8080/api}
    token: ${CATEDRA_TOKEN:eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJjZWxpIiwiZXhwIjoxODUzMTE3MTkyLCJhdXRoIjoiUk9MRV9VU0VSIiwiaWF0IjoxNzY2NzE3MTkyfQ.g5KbKaJcIDVPTl8kdXHcnA8a9Fvd4hK_fh9nZmvbwTGAV34zeJO0-xQFPKD09MAAK2GR9rG2zt93qdypBPccPg}
