package com.celi.backend.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TipoEventoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoEventoAllPropertiesEquals(TipoEvento expected, TipoEvento actual) {
        assertTipoEventoAutoGeneratedPropertiesEquals(expected, actual);
        assertTipoEventoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoEventoAllUpdatablePropertiesEquals(TipoEvento expected, TipoEvento actual) {
        assertTipoEventoUpdatableFieldsEquals(expected, actual);
        assertTipoEventoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoEventoAutoGeneratedPropertiesEquals(TipoEvento expected, TipoEvento actual) {
        assertThat(actual)
            .as("Verify TipoEvento auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoEventoUpdatableFieldsEquals(TipoEvento expected, TipoEvento actual) {
        assertThat(actual)
            .as("Verify TipoEvento relevant properties")
            .satisfies(a -> assertThat(a.getNombre()).as("check nombre").isEqualTo(expected.getNombre()))
            .satisfies(a -> assertThat(a.getDescripcion()).as("check descripcion").isEqualTo(expected.getDescripcion()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoEventoUpdatableRelationshipsEquals(TipoEvento expected, TipoEvento actual) {
        // empty method
    }
}
